name: Deploy Client to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your repository's default branch
    paths: # Trigger workflow only if files in 'client/**' or the workflow file itself change
      - 'client/**'
      - '.github/workflows/client-deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: # This job now handles checkout, build, and artifact upload for the client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify Node.js version 20
        # working-directory will apply to subsequent steps if not overridden

      - name: Install dependencies
        working-directory: ./client # Specify working directory for this step
        run: npm install

      - name: Build application
        working-directory: ./client # Specify working directory for this step
        run: npm run build # This runs: parcel build index.html --dist-dir docs --public-url ./

      - name: Setup Pages
        # This action configures GitHub Pages for deployment.
        uses: actions/configure-pages@v4
        # No working-directory needed here as it operates on repository/GitHub settings

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory containing the built files.
          # Parcel builds to 'docs' inside the 'client' directory.
          path: './client/docs'

  deploy:
    needs: build # Depends on the build job to complete successfully
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
