name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your repository's default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Using v4 for latest features and security

      - name: Setup Pages
        # This action is not strictly necessary for simple static sites
        # but it's good practice if you have build steps in the future.
        # For now, it mainly helps in configuring the environment.
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Using v3
        with:
          # Path to the directory containing the files to be deployed.
          # For this project, it's the root directory.
          path: '.' 
          # The artifact will contain index.html, style.css, and script.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Using v4 for latest features and security
